export const shiftData = {
  workerName: "Rahul",
  greeting: "Good morning",
  shift: "Morning Shift",
  store: "Q-Mart Kothrud, Pune",
  scanned: 4,
  total: 10,
  streakCount: 5,
  restockCompleted: 4,
  restockTotal: 6,
  offline: true,
};

export const shelves = [
  { id: 3, name: "Shelf 3", category: "Staples & Grains", icon: "🌾", status: "green", lastScan: "Scanned 8:15 AM", note: "Compliant", priority: false },
  { id: 5, name: "Shelf 5", category: "Beverages", icon: "🍼", status: "green", lastScan: "Scanned 8:32 AM", note: "Compliant", priority: false },
  { id: 7, name: "Shelf 7", category: "Snacks & Biscuits", icon: "🍪", status: "red", lastScan: "Scanned 8:48 AM", note: "3 OOS items detected · Restock pending", priority: false },
  { id: 9, name: "Shelf 9", category: "Personal Care", icon: "🧼", status: "green", lastScan: "Scanned 9:05 AM", note: "Compliant", priority: false },
  { id: 2, name: "Shelf 2", category: "Dairy & Frozen", icon: "🥛", status: "grey", lastScan: "Last scan 6:22 AM", note: "Not scanned · 3+ hours ago", priority: true },
  { id: 4, name: "Shelf 4", category: "Cooking Oil & Masalas", icon: "🫙", status: "grey", lastScan: "Not scanned yet", note: "Pending scan", priority: false },
  { id: 6, name: "Shelf 6", category: "Household & Cleaning", icon: "🧴", status: "grey", lastScan: "Not scanned yet", note: "Pending scan", priority: false },
  { id: 8, name: "Shelf 8", category: "Baby & Health", icon: "🩺", status: "grey", lastScan: "Not scanned yet", note: "Pending scan", priority: false },
  { id: 10, name: "Shelf 10", category: "Breakfast & Cereals", icon: "🥣", status: "grey", lastScan: "Not scanned yet", note: "Pending scan", priority: false },
  { id: 1, name: "Shelf 1", category: "Checkout Impulse Zone", icon: "🛒", status: "grey", lastScan: "Not scanned yet", note: "Pending scan", priority: false },
];

/* ═══════════════════════════════════════
   PLANOGRAM DATA — Shelf 7: Snacks & Biscuits
   6 sections with shelf-level product data
   ═══════════════════════════════════════ */
/* ═══════════════════════════════════════
   STORE MANAGER DASHBOARD DATA
   Screen 2.1 — Morning Readiness / Store Heatmap
   ═══════════════════════════════════════ */
export const managerStore = {
  name: "Q-Mart Kothrud, Pune",
  date: "Wednesday, 25 March 2026",
  time: "10:15 AM",
  overallCompliance: 84.2,
  complianceYesterday: 78.6,
  totalShelves: 10,
  endCapZones: 2,
  checkoutZones: 1,
  lostSalesPerHour: 1240,
  lostSalesRate: 4.2, // ₹ per minute
};

export const managerShelves = [
  { id: 1,  category: "Checkout Impulse",     compliance: 92, oosItems: 2,  lastScan: "9:45 AM",  color: "lightgreen", icon: "🛒" },
  { id: 2,  category: "Dairy & Frozen",       compliance: 71, oosItems: 8,  lastScan: "9:52 AM",  color: "red",        icon: "🥛" },
  { id: 3,  category: "Staples & Grains",     compliance: 96, oosItems: 1,  lastScan: "8:15 AM",  color: "darkgreen",  icon: "🌾" },
  { id: 4,  category: "Cooking Oil & Masalas", compliance: 88, oosItems: 3,  lastScan: "10:02 AM", color: "lightgreen", icon: "🫙" },
  { id: 5,  category: "Beverages",            compliance: 91, oosItems: 2,  lastScan: "8:32 AM",  color: "lightgreen", icon: "🍼", vip: { brand: "Coca-Cola", type: "End-cap display", rent: "₹15,000/mo" } },
  { id: 6,  category: "Household & Cleaning",  compliance: 74, oosItems: 7,  lastScan: "10:08 AM", color: "amber",      icon: "🧴" },
  { id: 7,  category: "Snacks & Biscuits",    compliance: 79, oosItems: 4,  lastScan: "9:18 AM",  color: "amber",      icon: "🍪", vip: { brand: "Cadbury Dairy Milk Silk", type: "Promotional bay", compliance: 100 } },
  { id: 8,  category: "Baby & Health",        compliance: 94, oosItems: 1,  lastScan: "9:35 AM",  color: "lightgreen", icon: "🩺" },
  { id: 9,  category: "Personal Care",        compliance: 89, oosItems: 3,  lastScan: "9:05 AM",  color: "lightgreen", icon: "🧼" },
  { id: 10, category: "Breakfast & Cereals",  compliance: 87, oosItems: 3,  lastScan: "10:12 AM", color: "lightgreen", icon: "🥣" },
];

export const managerAlerts = [
  {
    id: 1,
    severity: "critical",
    shelf: 2,
    category: "Dairy & Frozen",
    icon: "🥛",
    products: "Mother Dairy Curd 400g OOS, Amul Butter low stock",
    topProduct: "Mother Dairy Curd 400g",
    lossPerHour: 480,
    lastScan: "9:52 AM",
    status: "Restock dispatched, pending",
  },
  {
    id: 2,
    severity: "critical",
    shelf: 6,
    category: "Household & Cleaning",
    icon: "🧴",
    products: "Surf Excel 1kg OOS, Vim Bar low stock, Harpic OOS",
    topProduct: "Surf Excel 1kg",
    lossPerHour: 340,
    lastScan: "10:08 AM",
    status: "Not yet dispatched",
  },
  {
    id: 3,
    severity: "warning",
    shelf: 7,
    category: "Snacks & Biscuits",
    icon: "🍪",
    products: "Parle-G 250g restocking, Kurkure OOS, Dairy Milk low",
    topProduct: "Kurkure Multi Grain",
    lossPerHour: 280,
    lastScan: "9:18 AM",
    status: "Restocking ETA 4 mins",
  },
];

export const managerRestockFeed = [
  { id: 1, time: "10:04 AM", worker: "Manoj",  action: "picking",    product: "Surf Excel 1kg × 5",       target: "Shelf 6",            done: false },
  { id: 2, time: "9:38 AM",  worker: "Manoj",  action: "restocked",  product: "Dairy Milk 50g × 3",       target: "Shelf 7, Section 5",  done: true },
  { id: 3, time: "9:33 AM",  worker: "Suresh", action: "restocking", product: "Kurkure Multi Grain × 6",  target: "Shelf 7, Section 3",  done: false },
  { id: 4, time: "9:31 AM",  worker: "Suresh", action: "restocked",  product: "Parle-G 250g × 4",        target: "Shelf 7, Section 2",  done: true },
];

/* ═══════════════════════════════════════
   ALL SHELF SECTIONS DATA
   Each shelf has sections with master & inspected images
   Place generated images in public/shelves/shelfN-name/
   ═══════════════════════════════════════ */
export const allShelfSections = {
  1: [
    { id: 1, name: "Gums & Mints", icon: "cookie",
      masterImage: "/shelves/shelf1-checkout/shelf1S1(master).png",
      shelves: { top: ["Center Fruit","Happydent","Pulse","Orbit"], eyeLevel: ["Mentos","Chlormint","Big Babol","Alpenliebe"], lower: ["Vicks","Halls","Kopiko"] },
      expectedProducts: ["Center Fruit","Happydent","Pulse","Orbit","Mentos","Chlormint","Big Babol","Alpenliebe","Vicks","Halls","Kopiko"],
      result: "pass", issues: [] },
    { id: 2, name: "Mini Chocolates & Impulse", icon: "gift",
      masterImage: "/shelves/shelf1-checkout/shelf1S2(master).png",
      shelves: { top: ["KitKat","Gems","Munch"], eyeLevel: ["Dairy Milk","Snickers","Perk","Five Star"], lower: ["Eclairs","Mango Bite","Chocobakes"] },
      expectedProducts: ["KitKat","Gems","Munch","Dairy Milk","Snickers","Perk","Five Star","Eclairs","Mango Bite","Chocobakes"],
      result: "fail", issues: [{ type: "misplaced", product: "Local unbranded candy", detail: "Unauthorized product placed among premium items", shelf: "eyeLevel", correctLocation: "Remove from shelf" }] },
    { id: 3, name: "Essentials & Travel-size", icon: "first-aid",
      masterImage: "/shelves/shelf1-checkout/shelf1S3(master).png",
      shelves: { top: ["Dettol Soap","Vaseline Mini","Gillette Guard"], eyeLevel: ["Duracell AA","Duracell AAA","Band-Aid strips"], lower: ["Hand Sanitizer 50ml","Tissues Pack","Wet Wipes"] },
      expectedProducts: ["Dettol Soap","Vaseline Mini","Gillette Guard","Duracell AA","Duracell AAA","Band-Aid strips","Hand Sanitizer 50ml","Tissues Pack","Wet Wipes"],
      result: "pass", issues: [] },
  ],
  2: [
    { id: 1, name: "Milk & Curd", icon: "drop",
      masterImage: "/shelves/shelf2-dairy/shelf2S1(master).png",
      shelves: { top: ["Mother Dairy Milk 500ml","Amul Taaza 500ml","Amul Gold 1L"], eyeLevel: ["Mother Dairy Curd 200g","Mother Dairy Curd 400g","Amul Masti Curd"], lower: ["Amul Buttermilk 200ml","Mother Dairy Lassi"] },
      expectedProducts: ["Mother Dairy Milk 500ml","Amul Taaza 500ml","Amul Gold 1L","Mother Dairy Curd 200g","Mother Dairy Curd 400g","Amul Masti Curd","Amul Buttermilk 200ml","Mother Dairy Lassi"],
      result: "fail", issues: [{ type: "oos", product: "Mother Dairy Curd 400g", detail: "Completely OOS — slot empty", shelf: "eyeLevel", facingsExpected: 2, facingsFound: 0, qtyNeeded: 6 }] },
    { id: 2, name: "Butter, Cheese & Paneer", icon: "package",
      masterImage: "/shelves/shelf2-dairy/shelf2S2(master).png",
      shelves: { top: ["Amul Butter 100g","Amul Butter 500g"], eyeLevel: ["Amul Cheese Slices","Amul Cheese Cubes","Go Cheese Spread"], lower: ["Amul Fresh Paneer 200g","Amul Fresh Paneer 500g"] },
      expectedProducts: ["Amul Butter 100g","Amul Butter 500g","Amul Cheese Slices","Amul Cheese Cubes","Go Cheese Spread","Amul Fresh Paneer 200g","Amul Fresh Paneer 500g"],
      result: "fail", issues: [{ type: "oos", product: "Amul Butter 100g", detail: "Low stock — only 2 packs left", shelf: "top", facingsExpected: 4, facingsFound: 2, qtyNeeded: 4 }] },
    { id: 3, name: "Yogurt & Flavoured Dairy", icon: "bowl-food",
      masterImage: "/shelves/shelf2-dairy/shelf2S3(master).png",
      shelves: { top: ["Epigamia Greek Yogurt Strawberry","Epigamia Greek Yogurt Blueberry"], eyeLevel: ["Amul Lassi 200ml","Amul Kool Kesar","Amul Kool Badam"], lower: ["Mishti Doi Cup","Dahi Vada Kit"] },
      expectedProducts: ["Epigamia Greek Yogurt Strawberry","Epigamia Greek Yogurt Blueberry","Amul Lassi 200ml","Amul Kool Kesar","Amul Kool Badam","Mishti Doi Cup","Dahi Vada Kit"],
      result: "pass", issues: [] },
    { id: 4, name: "Ice Cream", icon: "snowflake",
      masterImage: "/shelves/shelf2-dairy/shelf2S4(master).png",
      shelves: { top: ["Kwality Walls Cornetto","Magnum Classic"], eyeLevel: ["Amul Sundae Cup","Kwality Walls Feast"], lower: ["Amul Tub 1L Vanilla","Naturals Tub Sitaphal"] },
      expectedProducts: ["Kwality Walls Cornetto","Magnum Classic","Amul Sundae Cup","Kwality Walls Feast","Amul Tub 1L Vanilla","Naturals Tub Sitaphal"],
      result: "pass", issues: [] },
    { id: 5, name: "Frozen Vegetables & Ready-to-eat", icon: "carrot",
      masterImage: "/shelves/shelf2-dairy/shelf2S5(master).png",
      shelves: { top: ["Safal Frozen Peas 500g","Safal Frozen Corn 500g"], eyeLevel: ["McCain French Fries","McCain Aloo Tikki"], lower: ["Frozen Paratha Pack","Frozen Samosa Pack"] },
      expectedProducts: ["Safal Frozen Peas 500g","Safal Frozen Corn 500g","McCain French Fries","McCain Aloo Tikki","Frozen Paratha Pack","Frozen Samosa Pack"],
      result: "fail", issues: [{ type: "misplaced", product: "Safal Frozen Peas", detail: "Found in dairy section instead of frozen", shelf: "eyeLevel", correctLocation: "Frozen Vegetables section" }] },
  ],
  3: [
    { id: 1, name: "Rice", icon: "grain",
      masterImage: "/shelves/shelf3-staples/shelf3S1(master).png",
      shelves: { top: ["India Gate Basmati 1kg","Daawat Basmati 1kg"], eyeLevel: ["India Gate Basmati 5kg","Fortune Basmati 5kg"], lower: ["Local Sona Masoori 5kg","Kolam Rice 5kg"] },
      expectedProducts: ["India Gate Basmati 1kg","Daawat Basmati 1kg","India Gate Basmati 5kg","Fortune Basmati 5kg","Local Sona Masoori 5kg","Kolam Rice 5kg"],
      result: "pass", issues: [] },
    { id: 2, name: "Atta & Flour", icon: "package",
      masterImage: "/shelves/shelf3-staples/shelf3S2(master).png",
      shelves: { top: ["Aashirvaad Atta 1kg","Pillsbury Atta 1kg"], eyeLevel: ["Aashirvaad Atta 5kg","Fortune Chakki Fresh 5kg"], lower: ["Besan 500g","Rava/Sooji 500g","Maida 1kg"] },
      expectedProducts: ["Aashirvaad Atta 1kg","Pillsbury Atta 1kg","Aashirvaad Atta 5kg","Fortune Chakki Fresh 5kg","Besan 500g","Rava/Sooji 500g","Maida 1kg"],
      result: "pass", issues: [] },
    { id: 3, name: "Dal & Pulses", icon: "bowl-food",
      masterImage: "/shelves/shelf3-staples/shelf3S3(master).png",
      shelves: { top: ["Tata Sampann Toor Dal 1kg","Tata Sampann Moong Dal 1kg"], eyeLevel: ["Chana Dal 1kg","Masoor Dal 1kg","Urad Dal 1kg"], lower: ["Rajma 500g","Chole/Kabuli Chana 500g"] },
      expectedProducts: ["Tata Sampann Toor Dal 1kg","Tata Sampann Moong Dal 1kg","Chana Dal 1kg","Masoor Dal 1kg","Urad Dal 1kg","Rajma 500g","Chole/Kabuli Chana 500g"],
      result: "pass", issues: [] },
    { id: 4, name: "Sugar & Salt", icon: "cube",
      masterImage: "/shelves/shelf3-staples/shelf3S4(master).png",
      shelves: { top: ["Tata Salt 1kg","Catch Salt 1kg","Rock Salt 500g"], eyeLevel: ["Sugar 1kg","Sugar 5kg"], lower: ["Jaggery Powder 500g","Mishri/Rock Sugar"] },
      expectedProducts: ["Tata Salt 1kg","Catch Salt 1kg","Rock Salt 500g","Sugar 1kg","Sugar 5kg","Jaggery Powder 500g","Mishri/Rock Sugar"],
      result: "fail", issues: [{ type: "oos", product: "Jaggery Powder 500g", detail: "Completely OOS — slot empty", shelf: "lower", facingsExpected: 2, facingsFound: 0, qtyNeeded: 4 }] },
  ],
  4: [
    { id: 1, name: "Cooking Oils", icon: "drop",
      masterImage: "/shelves/shelf4-cooking/shelf4S1(master).png",
      shelves: { top: ["Fortune Sunflower 1L","Saffola Gold 1L"], eyeLevel: ["Fortune Sunflower 5L","Nature Fresh 5L"], lower: ["Dhara Mustard Oil 1L","Gemini Groundnut Oil 1L"] },
      expectedProducts: ["Fortune Sunflower 1L","Saffola Gold 1L","Fortune Sunflower 5L","Nature Fresh 5L","Dhara Mustard Oil 1L","Gemini Groundnut Oil 1L"],
      result: "fail", issues: [{ type: "oos", product: "Fortune Sunflower 5L", detail: "Only 1 of 3 facings left — low stock", shelf: "eyeLevel", facingsExpected: 3, facingsFound: 1, qtyNeeded: 4 }] },
    { id: 2, name: "Powdered Masalas", icon: "fire",
      masterImage: "/shelves/shelf4-cooking/section2-masalas-master.jpg",
      shelves: { top: ["MDH Turmeric 100g","MDH Chili Powder 100g","MDH Garam Masala 100g"], eyeLevel: ["Everest Turmeric 100g","Everest Chili Powder 100g","Everest Coriander 100g"], lower: ["Catch Turmeric 200g","Catch Chili 200g"] },
      expectedProducts: ["MDH Turmeric 100g","MDH Chili Powder 100g","MDH Garam Masala 100g","Everest Turmeric 100g","Everest Chili Powder 100g","Everest Coriander 100g","Catch Turmeric 200g","Catch Chili 200g"],
      result: "fail", issues: [{ type: "misplaced", product: "Everest Chili Powder", detail: "Placed in MDH section", shelf: "top", correctLocation: "Eye-level, Position 2" }] },
    { id: 3, name: "Whole Spices & Condiments", icon: "leaf",
      masterImage: "/shelves/shelf4-cooking/section3-spices-master.jpg",
      shelves: { top: ["Cumin Seeds 100g","Mustard Seeds 100g","Cloves 50g"], eyeLevel: ["Mother's Pickle 300g","Priya Pickle 300g"], lower: ["Papad (Lijjat)","Papad (Local brand)"] },
      expectedProducts: ["Cumin Seeds 100g","Mustard Seeds 100g","Cloves 50g","Mother's Pickle 300g","Priya Pickle 300g","Papad (Lijjat)","Papad (Local brand)"],
      result: "pass", issues: [] },
    { id: 4, name: "Sauces & Ready Pastes", icon: "bowl-food",
      masterImage: "/shelves/shelf4-cooking/section4-sauces-master.jpg",
      shelves: { top: ["Kissan Ketchup 500g","Maggi Hot & Sweet"], eyeLevel: ["Ching's Schezwan Chutney","Soy Sauce","Vinegar"], lower: ["Ginger Garlic Paste","Tamarind Paste"] },
      expectedProducts: ["Kissan Ketchup 500g","Maggi Hot & Sweet","Ching's Schezwan Chutney","Soy Sauce","Vinegar","Ginger Garlic Paste","Tamarind Paste"],
      result: "pass", issues: [] },
  ],
  5: [
    { id: 1, name: "Carbonated Drinks", icon: "beer-bottle",
      masterImage: "/shelves/shelf5-beverages/shelf5S1(master).png",
      shelves: { top: ["Coca-Cola 2L","Thums Up 2L","Sprite 2L"], eyeLevel: ["Coca-Cola 600ml","Coca-Cola 600ml","Thums Up 600ml","Sprite 600ml","Pepsi 600ml","Limca 600ml"], lower: ["Coca-Cola 300ml","Thums Up 300ml","Sprite 300ml"] },
      expectedProducts: ["Coca-Cola 2L","Thums Up 2L","Sprite 2L","Coca-Cola 600ml (x2)","Thums Up 600ml","Sprite 600ml","Pepsi 600ml","Limca 600ml","Coca-Cola 300ml","Thums Up 300ml","Sprite 300ml"],
      result: "fail", issues: [{ type: "misplaced", product: "Pepsi 600ml", detail: "Placed in Coca-Cola end-cap zone — competitor violation", shelf: "eyeLevel", correctLocation: "General beverages area" }] },
    { id: 2, name: "Juices & Nectars", icon: "orange-slice",
      masterImage: "/shelves/shelf5-beverages/section2-juices-master.jpg",
      shelves: { top: ["Real Mango 1L","Real Mixed Fruit 1L","Tropicana Orange 1L"], eyeLevel: ["Frooti 200ml","Frooti 200ml","Maaza 200ml","Maaza 200ml","Real 200ml"], lower: ["B Natural Litchi 1L","B Natural Guava 1L"] },
      expectedProducts: ["Real Mango 1L","Real Mixed Fruit 1L","Tropicana Orange 1L","Frooti 200ml (x2)","Maaza 200ml (x2)","Real 200ml","B Natural Litchi 1L","B Natural Guava 1L"],
      result: "pass", issues: [] },
    { id: 3, name: "Water", icon: "drop",
      masterImage: "/shelves/shelf5-beverages/section3-water-master.jpg",
      shelves: { top: ["Bisleri 500ml","Bisleri 500ml","Kinley 500ml","Kinley 500ml"], eyeLevel: ["Bisleri 1L","Kinley 1L","Aquafina 1L"], lower: ["Bisleri 2L","Kinley 2L"] },
      expectedProducts: ["Bisleri 500ml (x2)","Kinley 500ml (x2)","Bisleri 1L","Kinley 1L","Aquafina 1L","Bisleri 2L","Kinley 2L"],
      result: "pass", issues: [] },
    { id: 4, name: "Tea & Coffee", icon: "coffee",
      masterImage: "/shelves/shelf5-beverages/section4-tea-master.jpg",
      shelves: { top: ["Tata Tea Premium 500g","Brooke Bond Red Label 500g","Wagh Bakri 500g"], eyeLevel: ["Nescafe Classic 100g","Bru Instant 100g","Nescafe Sachet (x10)"], lower: ["Tata Tea Gold 250g","Society Tea 250g"] },
      expectedProducts: ["Tata Tea Premium 500g","Brooke Bond Red Label 500g","Wagh Bakri 500g","Nescafe Classic 100g","Bru Instant 100g","Nescafe Sachet (x10)","Tata Tea Gold 250g","Society Tea 250g"],
      result: "pass", issues: [] },
    { id: 5, name: "Health & Energy Drinks", icon: "lightning",
      masterImage: "/shelves/shelf5-beverages/section5-health-master.jpg",
      shelves: { top: ["Bournvita 500g Jar","Horlicks 500g Jar"], eyeLevel: ["Complan 500g","Glucon-D 1kg","Glucon-D Sachet (x6)"], lower: ["Red Bull 250ml","Sting 250ml"] },
      expectedProducts: ["Bournvita 500g Jar","Horlicks 500g Jar","Complan 500g","Glucon-D 1kg","Glucon-D Sachet (x6)","Red Bull 250ml","Sting 250ml"],
      result: "fail", issues: [{ type: "oos", product: "Glucon-D 1kg", detail: "Only 1 of 3 facings left", shelf: "eyeLevel", facingsExpected: 3, facingsFound: 1, qtyNeeded: 4 }] },
    { id: 6, name: "Milk-based & Lassi", icon: "drop",
      masterImage: "/shelves/shelf5-beverages/section6-milkbased-master.jpg",
      shelves: { top: ["Amul Kool Kesar 200ml","Amul Kool Badam 200ml"], eyeLevel: ["Amul Lassi 200ml","Amul Lassi 200ml","Mother Dairy Lassi"], lower: ["Amul Milkshake Chocolate","Amul Milkshake Strawberry"] },
      expectedProducts: ["Amul Kool Kesar 200ml","Amul Kool Badam 200ml","Amul Lassi 200ml (x2)","Mother Dairy Lassi","Amul Milkshake Chocolate","Amul Milkshake Strawberry"],
      result: "pass", issues: [] },
  ],
  6: [
    { id: 1, name: "Detergents", icon: "package",
      masterImage: "/shelves/shelf6-household/section1-detergents-master.jpg",
      shelves: { top: ["Surf Excel Easy Wash 500g","Tide Plus 500g"], eyeLevel: ["Surf Excel 1kg","Ariel 1kg","Rin 1kg"], lower: ["Surf Excel 2kg","Tide 2kg","Surf Excel Liquid 1L"] },
      expectedProducts: ["Surf Excel Easy Wash 500g","Tide Plus 500g","Surf Excel 1kg","Ariel 1kg","Rin 1kg","Surf Excel 2kg","Tide 2kg","Surf Excel Liquid 1L"],
      result: "fail", issues: [{ type: "oos", product: "Surf Excel 1kg", detail: "Completely OOS — slot empty", shelf: "eyeLevel", facingsExpected: 2, facingsFound: 0, qtyNeeded: 5 }] },
    { id: 2, name: "Dish Wash", icon: "drop",
      masterImage: "/shelves/shelf6-household/section2-dishwash-master.jpg",
      shelves: { top: ["Vim Bar 300g","Vim Bar 300g","Vim Bar 300g"], eyeLevel: ["Vim Liquid 500ml","Pril Gel 500ml"], lower: ["Steel Scrubber (3pk)","Scotch-Brite Sponge"] },
      expectedProducts: ["Vim Bar 300g (x3)","Vim Liquid 500ml","Pril Gel 500ml","Steel Scrubber (3pk)","Scotch-Brite Sponge"],
      result: "fail", issues: [{ type: "oos", product: "Vim Bar 300g", detail: "Low stock — only 1 of 3 bars left", shelf: "top", facingsExpected: 3, facingsFound: 1, qtyNeeded: 4 }] },
    { id: 3, name: "Floor & Toilet Cleaners", icon: "broom",
      masterImage: "/shelves/shelf6-household/section3-cleaners-master.jpg",
      shelves: { top: ["Lizol 500ml","Lizol 1L"], eyeLevel: ["Harpic 500ml","Harpic 1L","Domex 500ml"], lower: ["Colin Glass Cleaner 500ml","Mr. Muscle Kitchen"] },
      expectedProducts: ["Lizol 500ml","Lizol 1L","Harpic 500ml","Harpic 1L","Domex 500ml","Colin Glass Cleaner 500ml","Mr. Muscle Kitchen"],
      result: "fail", issues: [{ type: "oos", product: "Harpic 500ml", detail: "Completely OOS", shelf: "eyeLevel", facingsExpected: 2, facingsFound: 0, qtyNeeded: 4 }] },
    { id: 4, name: "Brooms & Mops", icon: "broom",
      masterImage: "/shelves/shelf6-household/section4-brooms-master.jpg",
      shelves: { top: ["Soft Broom","Hard Broom"], eyeLevel: ["Mop Stick","Mop Refill"], lower: ["Dustpan","Garbage Bags 10pk","Garbage Bags 30pk"] },
      expectedProducts: ["Soft Broom","Hard Broom","Mop Stick","Mop Refill","Dustpan","Garbage Bags 10pk","Garbage Bags 30pk"],
      result: "pass", issues: [] },
    { id: 5, name: "Fresheners & Insecticides", icon: "wind",
      masterImage: "/shelves/shelf6-household/section5-fresheners-master.jpg",
      shelves: { top: ["Odonil Air Freshener","Ambi Pur Freshener"], eyeLevel: ["Good Knight Liquid Refill","All Out Refill","All Out Device"], lower: ["Hit Spray 200ml","Laxman Rekha","Naphthalene Balls"] },
      expectedProducts: ["Odonil Air Freshener","Ambi Pur Freshener","Good Knight Liquid Refill","All Out Refill","All Out Device","Hit Spray 200ml","Laxman Rekha","Naphthalene Balls"],
      result: "pass", issues: [] },
  ],
  7: [
    { id: 1, name: "Premium Biscuits", icon: "cookie",
      masterImage: "/shelves/shelf7-snacks/shelf7S1(master).png",
      shelves: { top: ["Oreo","Hide & Seek","Milano"], eyeLevel: ["Dark Fantasy","Jim Jam","Bourbon"], lower: ["Good Day Butter","Good Day Cashew"] },
      expectedProducts: ["Oreo","Hide & Seek","Milano","Dark Fantasy","Jim Jam","Bourbon","Good Day Butter","Good Day Cashew"],
      result: "pass", issues: [] },
    { id: 2, name: "Value Biscuits", icon: "cookie",
      masterImage: "/shelves/shelf7-snacks/shelf7S2(master).png",
      shelves: { top: ["Parle-G 800g Family Pack","Parle-G 800g","Parle-G 800g","Marie Gold 250g"], eyeLevel: ["Parle-G 250g","Parle-G 250g","Parle-G 250g","Parle-G 250g","Parle-G 250g","Parle-G 250g","Krackjack","Krackjack","Krackjack","Krackjack"], lower: ["Tiger Glucose","Glucose-D"] },
      expectedProducts: ["Parle-G 800g Family Pack","Parle-G 800g","Marie Gold 250g","Parle-G 250g (x6)","Krackjack (x4)","Tiger Glucose","Glucose-D"],
      result: "fail", issues: [{ type: "oos", product: "Parle-G 250g", detail: "Only 2 of 6 facings present — 4 units OOS", shelf: "eyeLevel", gap: "18cm gap visible", facingsExpected: 6, facingsFound: 2, qtyNeeded: 4 }] },
    { id: 3, name: "Namkeen & Savoury", icon: "bowl-food",
      masterImage: "/shelves/shelf7-snacks/shelf7S3(master).png",
      shelves: { top: ["Haldiram's Aloo Bhujia 400g","Moong Dal 200g"], eyeLevel: ["Haldiram's Mixture","Kurkure Multi Grain","Kurkure Masala Munch"], lower: ["Bikaji Bhujia","Local brand"] },
      expectedProducts: ["Haldiram's Aloo Bhujia 400g","Moong Dal 200g","Haldiram's Mixture","Kurkure Multi Grain","Kurkure Masala Munch","Bikaji Bhujia","Local brand"],
      result: "fail", issues: [
        { type: "oos", product: "Kurkure Multi Grain", detail: "Completely OOS — entire slot empty", shelf: "eyeLevel", facingsExpected: 1, facingsFound: 0, qtyNeeded: 6 },
        { type: "misplaced", product: "Shree Ganesh Mixture", detail: "Placed in Kurkure Multi Grain slot", shelf: "eyeLevel", correctLocation: "Lower Shelf, Position 4" },
      ] },
    { id: 4, name: "Chips & Crisps", icon: "lightning",
      masterImage: "/shelves/shelf7-snacks/shelf7S4(master).png",
      shelves: { top: ["Lay's Classic 150g","Magic Masala 150g"], eyeLevel: ["Lay's 52g","Lay's 52g","Lay's 52g","Lay's 52g","Lay's 52g","Lay's 52g","Lay's 52g","Lay's 52g","Kurkure Chilli Chatka","Bingo Mad Angles"], lower: ["Uncle Chipps","Yellow Diamond"] },
      expectedProducts: ["Lay's Classic 150g","Magic Masala 150g","Lay's 52g (x8)","Kurkure Chilli Chatka","Bingo Mad Angles","Uncle Chipps","Yellow Diamond"],
      result: "pass", issues: [] },
    { id: 5, name: "Chocolates & Candy", icon: "gift",
      masterImage: "/shelves/shelf7-snacks/shelf7S5(master).png",
      shelves: { top: ["Dairy Milk Silk Bubbly","Silk Roast Almond","Bournville"], eyeLevel: ["Dairy Milk 50g","Dairy Milk 50g","Dairy Milk 50g","Dairy Milk 50g","Dairy Milk 50g","Dairy Milk 50g","Dairy Milk 50g","Dairy Milk 50g","5 Star","5 Star","5 Star","5 Star","5 Star","5 Star","Perk","Perk","Perk","Perk"], lower: ["Eclairs","Mango Bite","Pulse"] },
      expectedProducts: ["Dairy Milk Silk Bubbly","Silk Roast Almond","Bournville","Dairy Milk 50g (x8)","5 Star (x6)","Perk (x4)","Eclairs","Mango Bite","Pulse"],
      result: "fail", issues: [{ type: "oos", product: "Dairy Milk 50g", detail: "Only 5 of 8 facings present — 3 units OOS", shelf: "eyeLevel", gap: "Gap between 5 Star and remaining Dairy Milk", facingsExpected: 8, facingsFound: 5, qtyNeeded: 3 }] },
    { id: 6, name: "Health Snacks & Rusks", icon: "heart",
      masterImage: "/shelves/shelf7-snacks/shelf7S6(master).png",
      shelves: { top: ["NutriChoice Digestive","NutriChoice Oats"], eyeLevel: ["NutriChoice 5 Grain","Bisk Farm Sugarfree"], lower: ["Britannia Rusk 300g","Britannia Rusk 300g","Britannia Rusk 300g","Britannia Rusk 300g","Parle Rusk"] },
      expectedProducts: ["NutriChoice Digestive","NutriChoice Oats","NutriChoice 5 Grain","Bisk Farm Sugarfree","Britannia Rusk 300g (x4)","Parle Rusk"],
      result: "pass", issues: [] },
  ],
  8: [
    { id: 1, name: "Diapers & Wipes", icon: "baby",
      masterImage: "/shelves/shelf8-baby/section1-diapers-master.jpg",
      shelves: { top: ["Pampers S (4-8kg)","Pampers M (6-11kg)"], eyeLevel: ["MamyPoko Pants M","MamyPoko Pants L","MamyPoko Pants XL"], lower: ["Huggies Wipes 72pk","Johnson's Baby Wipes"] },
      expectedProducts: ["Pampers S (4-8kg)","Pampers M (6-11kg)","MamyPoko Pants M","MamyPoko Pants L","MamyPoko Pants XL","Huggies Wipes 72pk","Johnson's Baby Wipes"],
      result: "pass", issues: [] },
    { id: 2, name: "Baby Food & Formula", icon: "bowl-food",
      masterImage: "/shelves/shelf8-baby/section2-babyfood-master.jpg",
      shelves: { top: ["Cerelac Stage 1 (6m+)","Cerelac Stage 2 (8m+)"], eyeLevel: ["Cerelac Stage 3 (10m+)","Nestum Rice 300g"], lower: ["Nan Pro 1 400g","Nan Pro 2 400g"] },
      expectedProducts: ["Cerelac Stage 1 (6m+)","Cerelac Stage 2 (8m+)","Cerelac Stage 3 (10m+)","Nestum Rice 300g","Nan Pro 1 400g","Nan Pro 2 400g"],
      result: "pass", issues: [] },
    { id: 3, name: "Baby Toiletries", icon: "drop",
      masterImage: "/shelves/shelf8-baby/section3-toiletries-master.jpg",
      shelves: { top: ["Johnson's Baby Shampoo 200ml","Johnson's Baby Oil 200ml"], eyeLevel: ["Johnson's Baby Powder 200g","Himalaya Baby Cream"], lower: ["Sebamed Baby Wash","Mamaearth Baby Lotion"] },
      expectedProducts: ["Johnson's Baby Shampoo 200ml","Johnson's Baby Oil 200ml","Johnson's Baby Powder 200g","Himalaya Baby Cream","Sebamed Baby Wash","Mamaearth Baby Lotion"],
      result: "pass", issues: [] },
    { id: 4, name: "Health & First Aid", icon: "first-aid",
      masterImage: "/shelves/shelf8-baby/section4-health-master.jpg",
      shelves: { top: ["ORS Packets (x5)","Electral Powder"], eyeLevel: ["Dettol Antiseptic 120ml","Cotton Roll 100g","Band-Aid (10pk)"], lower: ["Dabur Chyawanprash 500g","Dabur Honey 500g"] },
      expectedProducts: ["ORS Packets (x5)","Electral Powder","Dettol Antiseptic 120ml","Cotton Roll 100g","Band-Aid (10pk)","Dabur Chyawanprash 500g","Dabur Honey 500g"],
      result: "fail", issues: [{ type: "oos", product: "ORS Packets", detail: "Low stock — only 1 of 3 strips left", shelf: "top", facingsExpected: 3, facingsFound: 1, qtyNeeded: 6 }] },
  ],
  9: [
    { id: 1, name: "Shampoo & Hair Care", icon: "drop",
      masterImage: "/shelves/shelf9-personal/section1-shampoo-master.jpg",
      shelves: { top: ["Head & Shoulders 340ml","Dove 340ml","Clinic Plus 340ml"], eyeLevel: ["Pantene 180ml","Sunsilk 180ml","TRESemme 180ml"], lower: ["Shampoo Sachets (strip)","Coconut Oil Parachute 200ml"] },
      expectedProducts: ["Head & Shoulders 340ml","Dove 340ml","Clinic Plus 340ml","Pantene 180ml","Sunsilk 180ml","TRESemme 180ml","Shampoo Sachets (strip)","Coconut Oil Parachute 200ml"],
      result: "pass", issues: [] },
    { id: 2, name: "Soaps & Body Wash", icon: "drop",
      masterImage: "/shelves/shelf9-personal/section2-soaps-master.jpg",
      shelves: { top: ["Lux 150g","Lux 150g","Dove 100g","Dove 100g"], eyeLevel: ["Dettol 125g","Dettol 125g","Pears 125g","Santoor 125g"], lower: ["Dove Body Wash 250ml","Nivea Body Wash 250ml"] },
      expectedProducts: ["Lux 150g (x2)","Dove 100g (x2)","Dettol 125g (x2)","Pears 125g","Santoor 125g","Dove Body Wash 250ml","Nivea Body Wash 250ml"],
      result: "fail", issues: [{ type: "oos", product: "Dettol 125g", detail: "Only 1 of 2 facings left", shelf: "eyeLevel", facingsExpected: 2, facingsFound: 1, qtyNeeded: 4 }] },
    { id: 3, name: "Toothpaste & Oral Care", icon: "tooth",
      masterImage: "/shelves/shelf9-personal/section3-oral-master.jpg",
      shelves: { top: ["Colgate MaxFresh 150g","Colgate Strong Teeth 200g"], eyeLevel: ["Pepsodent 150g","Sensodyne 80g","Close-Up 150g"], lower: ["Oral-B Toothbrush","Colgate Toothbrush","Listerine 250ml"] },
      expectedProducts: ["Colgate MaxFresh 150g","Colgate Strong Teeth 200g","Pepsodent 150g","Sensodyne 80g","Close-Up 150g","Oral-B Toothbrush","Colgate Toothbrush","Listerine 250ml"],
      result: "pass", issues: [] },
    { id: 4, name: "Deodorants & Fragrances", icon: "wind",
      masterImage: "/shelves/shelf9-personal/section4-deo-master.jpg",
      shelves: { top: ["Nivea Men Deo 150ml","Nivea Women Deo 150ml"], eyeLevel: ["Fogg 120ml","Wild Stone 150ml","Engage 150ml"], lower: ["Nivea Roll-On 50ml","Dove Roll-On 50ml"] },
      expectedProducts: ["Nivea Men Deo 150ml","Nivea Women Deo 150ml","Fogg 120ml","Wild Stone 150ml","Engage 150ml","Nivea Roll-On 50ml","Dove Roll-On 50ml"],
      result: "fail", issues: [{ type: "misplaced", product: "Cooking Masala Packet", detail: "Non-personal-care item found on shelf", shelf: "lower", correctLocation: "Shelf 4 — Cooking Oil & Masalas" }] },
    { id: 5, name: "Face Care & Skincare", icon: "sun",
      masterImage: "/shelves/shelf9-personal/section5-skincare-master.jpg",
      shelves: { top: ["Himalaya Face Wash 150ml","Clean & Clear 100ml"], eyeLevel: ["Garnier Men Face Wash","Nivea Moisturizer 100ml","Pond's Cold Cream"], lower: ["Lakme Sunscreen SPF50","Vaseline Body Lotion 200ml"] },
      expectedProducts: ["Himalaya Face Wash 150ml","Clean & Clear 100ml","Garnier Men Face Wash","Nivea Moisturizer 100ml","Pond's Cold Cream","Lakme Sunscreen SPF50","Vaseline Body Lotion 200ml"],
      result: "pass", issues: [] },
  ],
  10: [
    { id: 1, name: "Cereals & Oats", icon: "grain",
      masterImage: "/shelves/shelf10-breakfast/section1-cereals-master.jpg",
      shelves: { top: ["Kellogg's Cornflakes 475g","Kellogg's Chocos 375g"], eyeLevel: ["Kellogg's Muesli 500g","Bagrry's Muesli 500g","Saffola Oats 1kg"], lower: ["Quaker Oats 1kg","Quaker Oats 400g"] },
      expectedProducts: ["Kellogg's Cornflakes 475g","Kellogg's Chocos 375g","Kellogg's Muesli 500g","Bagrry's Muesli 500g","Saffola Oats 1kg","Quaker Oats 1kg","Quaker Oats 400g"],
      result: "pass", issues: [] },
    { id: 2, name: "Bread & Bakery", icon: "bread",
      masterImage: "/shelves/shelf10-breakfast/section2-bread-master.jpg",
      shelves: { top: ["White Bread 400g","Brown Bread 400g"], eyeLevel: ["Multigrain Bread 400g","Pav (6pk)"], lower: ["Britannia Rusk 300g","Milk Bread"] },
      expectedProducts: ["White Bread 400g","Brown Bread 400g","Multigrain Bread 400g","Pav (6pk)","Britannia Rusk 300g","Milk Bread"],
      result: "fail", issues: [{ type: "oos", product: "Brown Bread 400g", detail: "Completely OOS — slot empty", shelf: "top", facingsExpected: 2, facingsFound: 0, qtyNeeded: 4 }] },
    { id: 3, name: "Jams, Honey & Spreads", icon: "jar",
      masterImage: "/shelves/shelf10-breakfast/section3-jams-master.jpg",
      shelves: { top: ["Kissan Mixed Fruit Jam 500g","Kissan Mango Jam 500g"], eyeLevel: ["Pintola Peanut Butter 350g","Dr. Oetker Fun Foods PB"], lower: ["Dabur Honey 500g","Dabur Honey 250g"] },
      expectedProducts: ["Kissan Mixed Fruit Jam 500g","Kissan Mango Jam 500g","Pintola Peanut Butter 350g","Dr. Oetker Fun Foods PB","Dabur Honey 500g","Dabur Honey 250g"],
      result: "pass", issues: [] },
    { id: 4, name: "Instant Breakfast & Mixes", icon: "bowl-food",
      masterImage: "/shelves/shelf10-breakfast/section4-instant-master.jpg",
      shelves: { top: ["MTR Poha Mix 200g","MTR Upma Mix 200g"], eyeLevel: ["Gits Idli Mix 200g","Gits Dosa Mix 200g"], lower: ["MTR Rava Idli Mix","Instant Dosa Batter 500g"] },
      expectedProducts: ["MTR Poha Mix 200g","MTR Upma Mix 200g","Gits Idli Mix 200g","Gits Dosa Mix 200g","MTR Rava Idli Mix","Instant Dosa Batter 500g"],
      result: "fail", issues: [{ type: "misplaced", product: "Maggi Noodles", detail: "Wrong category — instant noodles placed among breakfast mixes", shelf: "lower", correctLocation: "Separate Instant Noodles section" }] },
  ],
};

/* Backward compatibility — shelf7Sections still exported for existing imports */
export const shelf7Sections = allShelfSections[7];
